# Generated by Django 2.1.7 on 2019-03-09 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ASIC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('note', models.TextField()),
                ('status', models.IntegerField()),
                ('packaged', models.BooleanField()),
                ('version', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('note', models.TextField()),
                ('position', models.IntegerField()),
                ('asic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.ASIC')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PCB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('note', models.TextField()),
                ('status', models.IntegerField()),
                ('version', models.CharField(max_length=100)),
                ('asics', models.ManyToManyField(through='tracking.Connection', to='tracking.ASIC')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('modification_date', models.DateTimeField(auto_now=True)),
                ('note', models.TextField()),
                ('result', models.IntegerField()),
                ('version', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NoiseTestResult',
            fields=[
                ('test_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tracking.TestResult')),
            ],
            options={
                'abstract': False,
            },
            bases=('tracking.testresult',),
        ),
        migrations.AddField(
            model_name='testresult',
            name='asics',
            field=models.ManyToManyField(to='tracking.ASIC'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='pcbs',
            field=models.ManyToManyField(to='tracking.PCB'),
        ),
        migrations.AddField(
            model_name='pcb',
            name='test_results',
            field=models.ManyToManyField(to='tracking.TestResult'),
        ),
        migrations.AddField(
            model_name='connection',
            name='pcb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracking.PCB'),
        ),
        migrations.AddField(
            model_name='asic',
            name='test_results',
            field=models.ManyToManyField(to='tracking.TestResult'),
        ),
    ]
