# Generated by Django 2.1.7 on 2019-03-09 20:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='version',
        ),
        migrations.AddField(
            model_name='testresult',
            name='name',
            field=models.CharField(choices=[('noise-test-v1', 'Standard noise test')], default=datetime.datetime(2019, 3, 9, 20, 48, 25, 295442, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asic',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='asic',
            name='packaged',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='asic',
            name='status',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='asic',
            name='test_results',
            field=models.ManyToManyField(null=True, to='tracking.TestResult'),
        ),
        migrations.AlterField(
            model_name='asic',
            name='version',
            field=models.CharField(choices=[('1', 'LArPix v1'), ('2', 'LArPix v2')], max_length=100),
        ),
        migrations.AlterField(
            model_name='connection',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='position',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pcb',
            name='asics',
            field=models.ManyToManyField(null=True, through='tracking.Connection', to='tracking.ASIC'),
        ),
        migrations.AlterField(
            model_name='pcb',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pcb',
            name='status',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pcb',
            name='test_results',
            field=models.ManyToManyField(null=True, to='tracking.TestResult'),
        ),
        migrations.AlterField(
            model_name='pcb',
            name='version',
            field=models.CharField(choices=[('4c-hpats', '4-chip high purity argon test stand anode'), ('28c-hpats', '28-chip high purity argon test stand anode')], max_length=100),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='asics',
            field=models.ManyToManyField(null=True, to='tracking.ASIC'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='note',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='pcbs',
            field=models.ManyToManyField(null=True, to='tracking.PCB'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='result',
            field=models.IntegerField(null=True),
        ),
    ]
