# Generated by Django 2.1.7 on 2019-03-09 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_auto_20190309_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asic',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asic',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asic',
            name='test_results',
            field=models.ManyToManyField(blank=True, null=True, to='tracking.TestResult'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='connection',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pcb',
            name='asics',
            field=models.ManyToManyField(blank=True, null=True, through='tracking.Connection', to='tracking.ASIC'),
        ),
        migrations.AlterField(
            model_name='pcb',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pcb',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pcb',
            name='test_results',
            field=models.ManyToManyField(blank=True, null=True, to='tracking.TestResult'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='asics',
            field=models.ManyToManyField(blank=True, null=True, to='tracking.ASIC'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='pcbs',
            field=models.ManyToManyField(blank=True, null=True, to='tracking.PCB'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='result',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
