# Generated by Django 2.1.7 on 2019-03-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_auto_20190309_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asic',
            name='test_results',
            field=models.ManyToManyField(blank=True, to='tracking.TestResult'),
        ),
        migrations.AlterField(
            model_name='pcb',
            name='asics',
            field=models.ManyToManyField(blank=True, through='tracking.Connection', to='tracking.ASIC'),
        ),
        migrations.AlterField(
            model_name='pcb',
            name='test_results',
            field=models.ManyToManyField(blank=True, to='tracking.TestResult'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='asics',
            field=models.ManyToManyField(blank=True, to='tracking.ASIC'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='pcbs',
            field=models.ManyToManyField(blank=True, to='tracking.PCB'),
        ),
    ]
