# Generated by Django 2.1.7 on 2019-03-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_auto_20190309_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asic',
            name='status',
            field=models.CharField(choices=[('F', 'Fail'), ('P', 'Pass'), ('W', 'Weird')], max_length=100),
        ),
        migrations.AlterField(
            model_name='pcb',
            name='status',
            field=models.CharField(choices=[('F', 'Fail'), ('P', 'Pass'), ('W', 'Weird')], max_length=100),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='result',
            field=models.CharField(choices=[('F', 'Fail'), ('P', 'Pass'), ('W', 'Weird')], max_length=100),
        ),
    ]
